# 1. Importação das Bibliotecas

In [3]:
# Importação das bibliotecas
import pandas as pd
import json
import numpy as np
import matplotlib.pyplot as plt

# URL do dataset
url = "https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/main/TelecomX_Data.json"

# Carregar os dados
df = pd.read_json(url)

# Normalizar o JSON
df = pd.json_normalize(df)

# Visualizar
df.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

# 2. Extração dos Dados

In [4]:
import pandas as pd
import requests

url = "https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/main/TelecomX_Data.json"

data = requests.get(url).json()

df = pd.json_normalize(data)

df.head()

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,internet.OnlineSecurity,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

# 3. Transformação e Limpeza dos Dados

In [5]:
# Normalizar nomes das colunas
df.columns = df.columns.str.replace('.', '_')
df.columns

Index(['customerID', 'Churn', 'customer_gender', 'customer_SeniorCitizen',
       'customer_Partner', 'customer_Dependents', 'customer_tenure',
       'phone_PhoneService', 'phone_MultipleLines', 'internet_InternetService',
       'internet_OnlineSecurity', 'internet_OnlineBackup',
       'internet_DeviceProtection', 'internet_TechSupport',
       'internet_StreamingTV', 'internet_StreamingMovies', 'account_Contract',
       'account_PaperlessBilling', 'account_PaymentMethod',
       'account_Charges_Monthly', 'account_Charges_Total'],
      dtype='object')

In [6]:
# Converter variáveis numéricas
df['account_Charges_Total'] = pd.to_numeric(df['account_Charges_Total'], errors='coerce')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer_gender            7267 non-null   object
 3   customer_SeniorCitizen     7267 non-null   int64
 4   customer_Partner           7267 non-null   object
 5   customer_Dependents        7267 non-null   object
 6   customer_tenure            7267 non-null   int64
 7   phone_PhoneService         7267 non-null   object
 8   phone_MultipleLines        7267 non-null   object
 9   internet_InternetService   7267 non-null   object
 10  internet_OnlineSecurity    7267 non-null   object
 11  internet_OnlineBackup      7267 non-null   object
 12  internet_DeviceProtection  7267 non-null   object
 13  internet_TechSupport       7267 non-null   object
 14  internet_StreamingTV       7267 non-null   object
 15  internet_StreamingMovies   7267 non-null   object
 16  account_Contract           7267 non-null   object
 17  account_PaperlessBilling   7267 non-null   object
 18  account_PaymentMethod      7267 non-null   object
 19  account_Charges_Monthly    7267 non-null   float64
 20  account_Charges_Total      7256 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [8]:
# Tratar valores ausentes
df.isnull().sum()

customerID                    0
Churn                         0
customer_gender               0
customer_SeniorCitizen        0
customer_Partner              0
customer_Dependents           0
customer_tenure               0
phone_PhoneService            0
phone_MultipleLines           0
internet_InternetService      0
internet_OnlineSecurity       0
internet_OnlineBackup         0
internet_DeviceProtection     0
internet_TechSupport          0
internet_StreamingTV          0
internet_StreamingMovies      0
account_Contract              0
account_PaperlessBilling      0
account_PaymentMethod         0
account_Charges_Monthly       0
account_Charges_Total        11
dtype: int64

In [9]:
df = df.dropna()

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7256 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7256 non-null   object
 1   Churn                      7256 non-null   object
 2   customer_gender            7256 non-null   object
 3   customer_SeniorCitizen     7256 non-null   int64
 4   customer_Partner           7256 non-null   object
 5   customer_Dependents        7256 non-null   object
 6   customer_tenure            7256 non-null   int64
 7   phone_PhoneService         7256 non-null   object
 8   phone_MultipleLines        7256 non-null   object
 9   internet_InternetService   7256 non-null   object
 10  internet_OnlineSecurity    7256 non-null   object
 11  internet_OnlineBackup      7256 non-null   object
 12  internet_DeviceProtection  7256 non-null   object
 13  internet_TechSupport       7256 non-null   object
 14  internet_StreamingTV       7256 non-null   object
 15  internet_StreamingMovies   7256 non-null   object
 16  account_Contract           7256 non-null   object
 17  account_PaperlessBilling   7256 non-null   object
 18  account_PaymentMethod      7256 non-null   object
 19  account_Charges_Monthly    7256 non-null   float64
 20  account_Charges_Total      7256 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [11]:
# Criar variável alvo binária (Churn)
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

In [12]:
df['Churn'].value_counts()

Churn
0.0    5163
1.0    1869
Name: count, dtype: int64

In [13]:
df['Churn'].unique()

array([ 0.,  1., nan])

In [14]:
df = df.dropna(subset=['Churn'])

In [15]:
df['Churn'].unique()

array([0., 1.])

In [16]:
df.shape

(7032, 21)

# 4. Estrutura do Dataset

In [17]:
# Ver as colunas do dataset
df.columns

Index(['customerID', 'Churn', 'customer_gender', 'customer_SeniorCitizen',
       'customer_Partner', 'customer_Dependents', 'customer_tenure',
       'phone_PhoneService', 'phone_MultipleLines', 'internet_InternetService',
       'internet_OnlineSecurity', 'internet_OnlineBackup',
       'internet_DeviceProtection', 'internet_TechSupport',
       'internet_StreamingTV', 'internet_StreamingMovies', 'account_Contract',
       'account_PaperlessBilling', 'account_PaymentMethod',
       'account_Charges_Monthly', 'account_Charges_Total'],
      dtype='object')

In [18]:
# Ver tipos de dados
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7032 non-null   object
 1   Churn                      7032 non-null   float64
 2   customer_gender            7032 non-null   object
 3   customer_SeniorCitizen     7032 non-null   int64
 4   customer_Partner           7032 non-null   object
 5   customer_Dependents        7032 non-null   object
 6   customer_tenure            7032 non-null   int64
 7   phone_PhoneService         7032 non-null   object
 8   phone_MultipleLines        7032 non-null   object
 9   internet_InternetService   7032 non-null   object
 10  internet_OnlineSecurity    7032 non-null   object
 11  internet_OnlineBackup      7032 non-null   object
 12  internet_DeviceProtection  7032 non-null   object
 13  internet_TechSupport       7032 non-null   object
 14  internet_StreamingTV       7032 non-null   object
 15  internet_StreamingMovies   7032 non-null   object
 16  account_Contract           7032 non-null   object
 17  account_PaperlessBilling   7032 non-null   object
 18  account_PaymentMethod      7032 non-null   object
 19  account_Charges_Monthly    7032 non-null   float64
 20  account_Charges_Total      7032 non-null   float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.2+ MB

# Nova seção

# 5. Dicionário de Dados

## Identificação das Variáveis Relevantes

Após explorar o dataset, foram identificadas algumas variáveis importantes para a análise de evasão de clientes (Churn).

### Perfil do Cliente
Essas variáveis descrevem características demográficas dos clientes:
- customer_gender
- customer_SeniorCitizen
- customer_Partner
- customer_Dependents

### Tempo de Relacionamento
- customer_tenure  
Representa o tempo de permanência do cliente na empresa.

### Serviços Contratados
Essas variáveis indicam quais serviços adicionais o cliente possui:
- internet_InternetService
- internet_OnlineSecurity
- internet_OnlineBackup
- internet_DeviceProtection
- internet_TechSupport
- internet_StreamingTV
- internet_StreamingMovies

### Informações de Contrato e Pagamento
Essas variáveis podem influenciar diretamente a decisão de cancelamento:
- account_Contract
- account_PaperlessBilling
- account_PaymentMethod

### Informações Financeiras
- account_Charges_Monthly
- account_Charges_Total

### Identificador do Cliente
A coluna `customerID` é apenas um identificador único e não será utilizada na análise.

# 6. Verificando Inconsistências nos Dados

In [ ]:
# Tratar valores ausentes - já executado
# Conversão de variáveis numéricas - já executado
# Variável alvo (Churn) - já executado

In [19]:
# Verificar duplicados
df.duplicated().sum()

np.int64(0)

In [20]:
# Verificar categorias estranhas
df['account_Contract'].unique()

array(['One year', 'Month-to-month', 'Two year'], dtype=object)